<?php
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Create slideshows using any image over internet with many other features.
 *
 * @note only hooks are here. For other function see slideshow_creator.inc
 * and slideshow_creator.cck.inc for spedific CCK functions
 */

// Add the CCK complement if the module is enabled
if (module_exists('content')) {
  require_once(drupal_get_path('module', 'slideshow_creator') . '/slideshow_creator.cck.inc');
}


function slideshow_creator_init() {
  // Add the CSS file
  drupal_add_css(drupal_get_path('module', 'slideshow_creator') . '/slideshow_creator.css');

  // Add the main JavaScript, that does all the magic
  drupal_add_js(drupal_get_path('module', 'slideshow_creator') . '/slideshow_creator.js', 'module', 'header');
  drupal_add_js(drupal_get_path('module', 'jquery_plugin') . '/jquery.cycle.min.js');
}

/**
 * Implements FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 *
 * Autocomplete_path is not used by text_widget but other widgets can use it
 * (see nodereference and userreference).
 */
function slideshow_creator_elements() {
  return array(
    'slideshow_creator' => array(
      '#input' => TRUE,
      '#columns' => array('value'),
      '#delta' => 0,
      '#process' => array('slideshow_creator_process'),
    ),
    'slideshow_creator_form' => array(
      '#input' => TRUE,
      '#columns' => array('ssc'),
      '#delta' => 0,
      '#element_validate' => array('_slideshow_creator_form_validate'),
      '#process' => array('_slideshow_creator_form_process'),
    ),
  );
}

/**
 * Implements hook_filter().
 */
function slideshow_creator_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'description':
      return t('Create true slideshows using any image over internet with many other features.');
    case 'list':
      return array(0 => t('Slideshow Creator'));
    case 'name':
      return t('Slideshow Creator');
    case 'no cache':
      return FALSE; /* TRUE for debugging, FALSE for production */
    case 'prepare':
      return $text;
    case 'process':
      include_once drupal_get_path('module', 'slideshow_creator') . '/slideshow_creator.inc';
      return _slideshow_creator_process_text($text);
  }
}

/**
 * Implements hook_filter_tips().
 */
function slideshow_creator_filter_tips($delta, $format, $long = FALSE) {
  return t('Slideshows can be added to this post.');
}

/**
 * Implements hook_menu().
 */
function slideshow_creator_menu() {
  $items['admin/settings/slideshow_creator'] = array(
    'access arguments' => array('administer filters'),
    'file' => 'slideshow_creator.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_slideshow_creator_admin'),
    'title' => 'Slideshow Creator',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function slideshow_creator_theme() {
  return array(
    'slideshow_creator' => array(
      'arguments' => array('ss' => NULL),
      'file' => 'slideshow_creator.inc',
    ),
    'slideshow_creator_form' => array(
      'arguments' => array('element' => NULL),
      'file' => 'slideshow_creator.cck.inc',
    ),
    'slideshow_creator_formatter_default' => array(
      'arguments' => array('ssid' => NULL),
      'file' => 'slideshow_creator.cck.inc',
    ),
  );
}
